// src/Content.js
import React from 'react';

function Content() {
  return (
    <main className="content">
     Merencanakan
PS C1
Harry Potter saat masih bayi

Bab 1: Anak Laki-Laki yang Hidup
" Kepada Harry Potter - Anak Laki-Laki yang Hidup "
— Orang-orang bertemu secara rahasia di seluruh negeri untuk bersulang untuk Harry
Vernon dan Petunia Dursley , dari Privet Drive Nomor Empat (di Little Whinging , Surrey ), dengan bangga mengatakan bahwa mereka normal-normal saja. Mereka adalah orang-orang terakhir yang Anda harapkan terlibat dalam sesuatu yang aneh atau misterius, karena mereka tidak tahan dengan omong kosong seperti itu. Vernon adalah direktur sebuah perusahaan pembuat bor bernama Grunnings , dan Petunia menjaga rumah serta membesarkan putra mereka yang berusia satu tahun, Dudley .

Pada hari Selasa, 1 November 1981 , keluarga Dursley memulai hari dengan bergosip tentang tetangga mereka sementara Petunia bergulat dengan Dudley yang tidak menyenangkan itu ke kursi tingginya. Tak satu pun dari mereka melihat burung hantu besar berwarna kuning kecoklatan terbang melewati jendela mereka, tapi Vernon melihat seekor kucing kucing membaca peta dan tanda jalan di luar rumah mereka. Dia memaksa dirinya untuk melupakan kucing itu, tapi saat tiba di kota, dia melihat sekelompok besar orang mengenakan jubah. Dia menguping mereka dan mendengar mereka berbicara tentang "keluarga Potter dan putra mereka Harry. " Vernon menganggap ini mengerikan karena keluarga Potter adalah mertuanya, dan dia serta Petunia tidak ingin ada orang yang mengetahui tentang mereka.

Ketika dia pulang kerja di penghujung hari, dia bertemu dengan seorang pria kecil yang mengenakan jubah, tapi ketika dia mencoba untuk meminta maaf, pria itu memeluknya dan mengatakan kepadanya bahwa bahkan muggle seperti dia harus merayakan hari ini karena "Kau-Tahu- Siapa" yang telah dikalahkan.

Vernon kembali ke rumah dan menemukan kucing itu masih menunggu di sana, dan itu hanya memberinya tatapan tegas ketika dia mencoba mengusirnya. Berita tersebut penuh dengan penampakan burung hantu dan pertunjukan kembang api yang tidak dapat dijelaskan, dan Vernon dengan gugup bertanya kepada Petunia apakah dia telah mendengar kabar dari saudara perempuannya baru-baru ini. Petunia kesal tetapi mengatakan kepadanya bahwa dia belum mendengar kabar dari saudara perempuannya dan nama keponakan mereka adalah "Harry." Hati Vernon tenggelam. Dia merasa sulit untuk tertidur malam itu tetapi akhirnya berhasil.

Setelah keluarga Dursley tertidur, Albus Dumbledore muncul di tengah Privet Drive dan menyedot cahaya dari lampu jalan dengan Deluminatornya . Dia menyapa kucing, yang menghabiskan sepanjang hari menunggu di luar, sebagai " Profesor McGonagall ", dan kucing itu berubah menjadi manusia wanita. Mereka membahas kematian James dan Lily Potter di tangan Lord Voldemort di pondok Potter di Godric's Hollow dan bagaimana bayi laki-laki mereka Harry Potter secara ajaib selamat dari serangan itu sementara Voldemort tampaknya telah meninggal.

Rubeus Hagrid tiba mengendarai sepeda motor terbang dan mengangkut Harry. Dia menyerahkannya kepada Dumbledore, yang meninggalkan bayi yang sedang tidur dan surat untuk keluarga Dursley di depan pintu Nomor Empat. Ketiga penyihir itu putus asa karena harus meninggalkan bayi yatim piatu itu bersama kerabatnya, namun mereka hanya memberikan waktu sejenak untuk berkabung sebelum memaksakan diri untuk pergi. Hagrid mengatakan dia akan mengembalikan sepeda motor itu kepada pemiliknya, Sirius Black muda ; McGonagall melanjutkan wujud kucingnya dan menyelinap di sudut jalan, dan Dumbledore mengembalikan lampu ke lampu jalan dan mengucapkan selamat tinggal pada Harry sebelum menghilang tanpa jejak.

Harry berguling ke dalam bungkusan selimutnya, dan tangan mungilnya menggenggam surat itu saat dia tidur. Dia tidak tahu bahwa dia istimewa dan terkenal, bahwa dia akan dibangunkan keesokan paginya oleh teriakan bibinya ketika Petunia membuka pintu depan untuk mengeluarkan botol-botol susu, bahwa dia akan menghabiskan beberapa minggu berikutnya ditusuk dan dicubit. oleh sepupunya Dudley, atau pada saat ini, orang-orang yang bertemu secara rahasia di seluruh negeri sedang bersulang, "Untuk Harry Potter -- anak laki-laki yang hidup!"

Bab 2: Kaca yang Hilang
" Bibi Petunia sering mengatakan bahwa Dudley tampak seperti bayi bidadari - Harry sering mengatakan bahwa Dudley tampak seperti babi yang memakai wig. "
— Deskripsi putra keluarga Dursley
PS C2
Dudley menghitung hadiahnya

Sepuluh tahun telah berlalu sejak keluarga Dursley terbangun dan menemukan Harry Potter tergeletak di depan pintu rumah mereka, dan Privet Drive serta rumah keluarga Dursley tidak berubah sejak hari itu. Satu-satunya perbedaan adalah banyaknya gambar Dudley Dursley sepanjang hidupnya yang dipajang di dinding. Tidak ada tanda-tanda Harry Potter tinggal di sana, karena dia terpaksa tinggal di lemari di bawah tangga , ruangan yang sangat sempit dengan banyak laba-laba. Petunia datang ke pintu rumah Harry suatu pagi dan membangunkannya dengan suara melengking. Harry mencoba memikirkan tentang mimpi yang dia alami. Itu tentang sepeda motor terbang , dan dia yakin dia pernah mengalami mimpi yang sama sebelumnya. Bibi Petunia menyuruhnya membuat bacon; dia ingin segalanya sempurna untuk ulang tahun Dudley yang ke-11. Harry mengenakan pakaian lama Dudley dan memasuki dapur, di mana mejanya dipenuhi hadiah Dudley.

Harry memiliki rambut hitam legam dan mata hijau. Tape menyatukan kacamatanya karena Dudley telah memecahkannya berkali-kali. Yang paling membedakan Harry dengan orang lain adalah bekas luka berbentuk kilat di dahinya. Dia sering bertanya-tanya bagaimana dia mendapatkannya, dan keluarga Dursley memberitahunya bahwa itu berasal dari kecelakaan mobil yang menewaskan orang tua Harry. Harry tidak tahu lebih banyak tentang kecelakaan ini karena peraturan pertama keluarga Dursley adalah tidak bertanya. Dudley masuk ke dapur dan mulai menghitung hadiahnya, hanya untuk menemukan 36, yang dengan marah dia ingat bahwa jumlahnya berkurang satu dari tahun sebelumnya. Bibi Petunia menyatakan bahwa mereka akan membelikannya dua hadiah baru saat mereka keluar. Vernon memberi tahu Petunia bahwa tetangga mereka, Arabella Figg , kakinya patah dan tidak bisa merawat Harry saat mereka berada di kebun binatang . Mereka tidak bisa memikirkan orang lain yang bisa merawatnya, jadi Harry harus pergi bersama mereka.

Dudley diizinkan mengajak temannya ke kebun binatang dan memilih temannya Piers Polkiss . Piers datang ke rumah bersama ibunya . Setengah jam kemudian, Harry duduk di dalam mobil bersama Dudley, Piers, Vernon, dan Petunia. Di tengah perjalanan, sebuah sepeda motor menyusul mereka, dan Vernon mengeluh tentang mereka. Harry berkomentar bahwa dia bermimpi tentang sepeda motor terbang, dan Vernon dengan cepat mengingatkannya bahwa sepeda motor tidak bisa terbang. Harry memikirkan semua hal aneh yang terjadi padanya: dia pernah melompat ke cerobong asap sekolah dan secara misterius menumbuhkan kembali seluruh rambutnya di pagi hari setelah potong rambut. Di kebun binatang, Dudley dan Piers menganggap binatang itu membosankan. Harry dibiarkan mengawasi Boa constrictor saat ia tidur, dan ketika Dudley mencoba membuatnya bergerak, ia bangun tetapi tetap tidak bergerak. Ular itu mulai bergerak setelah Dudley dan Piers menyelinap pergi. Beberapa saat kemudian, Harry berbicara kepada ular itu dan secara ajaib menemukan ular itu memahaminya. Setelah menyadari bahwa ular itu sekarang bergerak, Piers memanggil Dudley dan Vernon kembali ke pameran ular itu. Dudley mendorong Harry menyingkir (dia mendarat "dengan keras di lantai beton") dan menempelkan wajahnya ke kaca. Harry menjadi marah, dan entah bagaimana kacanya hilang , dan ular itu keluar, menakuti Dudley dan Piers. Saat ular itu merayap menjauh, Harry mengira dia mendengarnya berbicara kembali kepadanya. Piers mengadu pada Harry bahwa dia telah berbicara dengan ular itu, dan Paman Vernon mengirimnya ke lemarinya – tanpa makan selama seminggu sebagai hukuman yang kejam.

Bab 3: Surat-Surat dari Siapa Pun
Dudley : " Ayah! Lihat, Harry punya surat! "
Paman Vernon : " Apa? Siapa yang menulis surat padamu? "
— Vernon Dursley mengambil surat Harry darinya
PS C3
Ratusan surat tiba di perapian

Sejak ular boa melarikan diri dari kebun binatang, Harry dikurung di lemarinya untuk waktu yang paling lama. Ini adalah awal liburan musim panas ketika Harry akhirnya diizinkan keluar. Meski tidak bersekolah, Harry tetap tidak bisa lepas dari Dudley dan gengnya yang rutin berkunjung ke rumah tersebut. Untuk menghindari mereka, Harry biasanya berkeliaran di sekitar Privet Drive . Namun dia senang Dudley dan Piers bersekolah di Smeltings Academy sementara Harry bersekolah di Stonewall High . Suatu hari selama musim panas, Harry disuruh mengambilkan jabatan untuk Paman Vernon. Ketika Harry pergi mengambil surat, ada tiga surat: kartu pos dari saudara perempuan Paman Vernon , yang sedang berlibur di Pulau Wight, surat yang terlihat seperti tagihan, dan surat untuk Harry. Harry mengambil surat itu, mempelajari perkamen kuning bahan pembuatnya, dan kemudian membaca alamatnya:

Tuan H. Potter

Lemari Di Bawah Tangga

4, Drive Privet

Rengekan Kecil

Surrey

Harry tidak percaya. Dia belum pernah menerima surat seumur hidupnya. Di bagian belakang terdapat segel lilin dengan gambar Singa, Ular, Luak, dan Elang yang mengelilingi huruf H. Harry kembali ke dapur dan memberikan dua surat lainnya kepada Paman Vernon ketika dia duduk dan mulai membuka surat itu. Dudley segera melihat bahwa Harry memiliki surat, dan Paman Vernon mengambilnya untuk dibaca bersama Bibi Petunia . Paman Vernon menyuruh Harry dan Dudley keluar dari dapur, jadi mereka berdua pergi dan berdiri di aula. Keduanya berebut siapa yang bisa melihat melalui lubang kunci. Dudley menang, jadi Harry terpaksa melihat melalui celah antara lantai dan pintu. Paman Vernon dan Bibi Petunia sedang mendiskusikan segel di bagian belakang. Paman Vernon berkata sebaiknya mereka mengabaikannya saja.

Kemudian, ketika Harry berada di lemarinya, Paman Vernon masuk dan mengatakan bahwa dia telah membakar surat itu dan mereka memindahkannya ke kamar tidur kedua Dudley . Sedikit terkejut, Harry memindahkan semua barangnya ke kamar tidur, berharap dia mendapatkan suratnya. Keesokan paginya saat sarapan, Dudley diminta mengambil pos oleh Paman Vernon. Setelah menggedor-gedor aula dengan tongkat Smeltingnya, Dudley mengetahui bahwa surat lain ditujukan kepada Harry, kali ini di '''Kamar Tidur Terkecil''' daripada '''Lemari di Bawah Tangga''' . Harry dan Paman Vernon bergegas ke lorong untuk mengambil surat itu. Setelah satu menit pertarungan yang membingungkan, Paman Vernon muncul sambil memegang surat di tangannya.

Determined to see what his letter says, Harry creeps down the stairs early the following day and approaches the door. He is going to camp there until the post arrives, and then he will finally get to read his letter. When he reaches the door, however, he stands on Uncle Vernon - who has had the very same idea. Every day, letters appear addressed to Harry, doubling in number. Eventually, so many letters arrive that Uncle Vernon resorts to nailing shut the letterbox. But they begin to appear in the strangest places: under the door, squeezed through the window, and Aunt Petunia even finds some while cracking open eggs. Finally, they get attacked by thirty or forty letters being fired out of the fireplace. Despite the sender's efforts, Harry still does not manage to get his hands on one of the letters long enough to read it, and a furious Uncle Vernon states that they are leaving the house. They get into their car and leave ten minutes later.

They travel for miles until they eventually stop in front of a gloomy hotel on the brink of the city. However, Vernon's attempts to shake the sender off are unsuccessful, as more letters come for Harry to the hotel the next morning. Again, they return to the car and finally stop to get on a boat that takes them to an island with a small hut. Harry remembers that the next day will be his eleventh birthday. Harry can't sleep with the raging storm outside when they get there, so he counts down the time until his birthday. When Dudley's watch turns to the next day, there is a loud knocking at the door - something wants to get in...

Chapter 4: The Keeper of the Keys
"Harry – yer a wizard."
— Hagrid telling Harry that he is a wizard
PS C4
Rubeus Hagrid enters the cabin

There is another loud boom on the door, and Dudley wakes up, thinking it is a cannon. Uncle Vernon comes through with a rifle, with Aunt Petunia cowering behind him. The door is blasted off its hinges and hits the floor. A giant enters and fixes the door into its frame. The giant asks for coffee and sits on the couch beside Dudley, scaring him away to hide behind Aunt Petunia. The giant turns his eyes to Harry and greets him, saying he hasn't seen him since he was a baby. He says Harry looks like his father but has his mother's eyes. Uncle Vernon tells him to leave, but the giant merely grabs the gun, ties into a knot and throws it away. The giant presents Harry with a birthday cake. Harry asks the giant who he is, and he says he is Rubeus Hagrid, the Keeper of Keys and Grounds at Hogwarts School of Witchcraft and Wizardry. Hagrid makes a fire and cooks some sausages. He is shocked to discover that Harry knows nothing about Hogwarts. He gets angry at the Dursleys for not telling him anything about his parents' world, his world. Harry has no idea what's going on. Hagrid tells Harry his parents are famous and that he's a wizard, despite Uncle Vernon forbidding him. Hagrid gives Harry the letter that he has been craving. It tells him that he has been accepted into Hogwarts School of Witchcraft and Wizardry and that term begins on 1st September.

Surat Harry
Hagrid takes out parchment and a quill and writes a letter to Hogwarts Headmaster Albus Dumbledore, explaining he has given Harry the letter. Uncle Vernon tells Hagrid that Harry won't be going, but the giant knows that a great Muggle like him can't stop Harry from going to Hogwarts. Uncle Vernon reveals he knew that Harry's a wizard, and Aunt Petunia tells Harry that her sister, Harry's mother, was a witch. Petunia said another wizard killed them, and Harry screams that Petunia said they got killed in a car crash. Hagrid is as outraged as Harry is that the Dursleys have lied that much. He sits down and tells Harry that a Dark wizard named Lord Voldemort killed Harry's parents and tried to kill Harry too. But the spell he used backfired, only leaving Harry his scar. Hagrid tells him that he brought Harry from the ruins of the house and brought him to the Dursleys' house on 4 Privet Drive. Uncle Vernon says it's a load of rubbish and tries to persuade Harry that whatever happened to his parents was deserved anyway, but Hagrid pulls an umbrella out of his coat and threatens Uncle Vernon. Harry asks what happened to Voldemort, and Hagrid tells him he vanished and hasn't been seen since.

Harry doubts he is a wizard until Hagrid asks if he ever made anything he couldn't explain happen when he was angry or scared. When Uncle Vernon makes the mistake of mocking Dumbledore, Hagrid swishes the umbrella in Dudley's direction, and Dudley sprouts a curly pig's tail. Hagrid asks Harry not to mention it at Hogwarts because Hagrid isn't allowed to do magic since he was expelled. Hagrid takes off his coat, and Harry sleeps under it for the rest of the night, waiting for the day ahead.

Chapter 5: Diagon Alley
"Harry wished he had about eight more eyes. He turned his head in every direction as they walked up the street, trying to look at everything at once: the shops, the things outside them, the people doing their shopping."
— Harry in Diagon Alley
PS C5
Ollivander's Wand Shop

When Harry wakes the following day, he tries to tell himself that what happened the previous night had all been a dream and that Hagrid taking him to a school for wizards called Hogwarts School of Witchcraft and Wizardry had never happened. But when he opens his eyes, Hagrid has fallen asleep on the couch, and he discovers that it has all happened. He hears a tapping noise coming from the window and lets in an owl. The owl drops a newspaper on Hagrid's lap and begins to claw Hagrid's coat. Hagrid tells Harry to pay the owl, so Harry does what he says, and the owl leaves. Hagrid tells him they have to go and buy his things, but Harry worries because he hasn't got any money. Hagrid tells him his parents didn't leave him without money and that their first stop is Gringotts, the wizard's bank. He explains that goblins run it and that "you'd be mad to try and rob it". Hagrid says Dumbledore also needs something from Gringotts, so Hagrid has to go get it.

They step outside the hut and step into their boat. Hagrid uses a bit of magic to speed things up for them. Hagrid says there are enchantments guarding the vaults in Gringotts. Gringotts is all under London; you would die of starvation trying to get out. Hagrid begins to read the Daily Prophet and mutters that the Ministry of Magic is messing things up as usual. Harry wonders what the Ministry of Magic does, and Hagrid explains that they handle everything to do with magic. He says they wanted Dumbledore for Minister, but Cornelius Fudge got the job. As they pass through London, people often stare at Hagrid due to his size and his pointing out things that Muggles are brilliant at inventing. Harry asks if there are Dragons guarding Gringotts. Hagrid says yes and mutters that he would like a dragon. Harry takes out his list and reads it out. It says he needs a set of robes, a pointed hat, dragon hide gloves, and a winter coat. There is a list of his books and stationary equipment. Hagrid leads them both into a pub called the Leaky Cauldron Harry did not notice was there. It is dark and shabby, and everyone greets Hagrid as he enters. When people see Harry, many shake his hand, including Doris Crockford and Dedalus Diggle. A man with a turban approaches them, and Hagrid introduces Harry to Quirinus Quirrell, the Defence Against the Dark Arts professor at Hogwarts. They talk for a bit then Hagrid steers them out a back door into a small enclosed area with a few barrels. Hagrid takes out his umbrella and taps bricks with it, counting an order. Once he is done, a hole appears in the brick wall, slowly getting bigger, until the wall disappears entirely, revealing a crowded street with people wearing robes everywhere with shops left and right. Hagrid tells Harry the street is called Diagon Alley.

Sambil berjalan di jalan, Harry mencoba melihat ke sekeliling, mengamati sebanyak mungkin. Di ujung Diagon Alley terdapat bangunan besar berwarna putih bersalju: Gringotts Bank. Sebuah peringatan bergema saat mereka masuk, memberitahu mereka untuk merampok dengan risiko mereka sendiri. Harry dan Hagrid menemui Goblin dan menjelaskan bahwa mereka perlu mengambil sejumlah uang dari lemari besi Harry. Goblin meminta kunci Harry, dan Hagrid memberikannya setelah memilah-milah banyak kunci lainnya. Goblin memanggil Goblin lain bernama Griphook untuk membawa mereka ke lemari besi. Hagrid juga menyatakan mereka harus diturunkan untuk menghapus Kau-Tahu-Apa di Vault 713 . Griphook membawa mereka ke lemari besi Harry, di mana ada sejumlah besar uang milik Harry yang menumpuk di sana. Ada Knut Perunggu , Sabit Perak , dan Galleon Emas . Harry dan Hagrid mengambil sejumlah uang untuk daftar Harry, lalu meninggalkan Gringotts. Hagrid harus berdiri sebentar ketika kereta yang membawa mereka ke brankas membuatnya merasa mual . Griphook kemudian membawa mereka ke Vault 713, tempat Hagrid mengeluarkan paket kecil yang kotor tetapi tidak bisa memberi tahu Harry apa itu.

Hagrid pergi minum di Leaky Cauldron sementara Harry mendapatkan seragamnya di Jubah Madam Malkin untuk Segala Acara . Madam Malkin mendudukkannya di bangku di samping seorang anak laki-laki berwajah pucat yang juga mengukur jubahnya. Anak laki-laki itu mulai berbicara tentang Quidditch , termasuk rencananya untuk menyelundupkan sapunya dan rumah-rumah bernama Slytherin dan Hufflepuff . Ketika anak laki-laki itu mengetahui bahwa Harry ada di sana bersama Hagrid, dia bertanya kepadanya apa yang terjadi dengan orang tuanya. Dia tidak simpatik atas kematian mereka dan hanya mengungkapkan kelegaan bahwa mereka berdua adalah penyihir karena jenis yang lain tidak boleh diizinkan masuk.

Ketika Harry pergi, dia bertanya kepada Hagrid tentang apa yang dikatakan anak itu, dan Hagrid menjelaskan bahwa ada empat rumah di Hogwarts, Quidditch adalah permainan yang dimainkan dengan sapu, dan status darah tidak menjadi masalah. Mereka terus berbelanja sampai yang dibutuhkan Harry hanyalah tongkatnya dan (Hagrid bersikeras) hadiah ulang tahun.

Di Ollivanders , toko tongkat sihir , Tuan Ollivander mengusir Harry dengan sikapnya yang menyeramkan saat mendiskusikan tongkat sihir yang dibeli oleh Hagrid, orang tua Harry, dan Voldemort. Ollivander menyentuh bekas luka Harry dan meminta maaf atas fakta bahwa dia menjual tongkat sihir yang menyebabkannya. Ollivander memberi Harry tongkat dan menyuruhnya melambaikannya. Harry melakukannya, tapi itu tidak cocok untuknya, jadi Ollivander mengambilnya kembali. Harry mencoba banyak tongkat sihir, tetapi tidak ada yang cukup berhasil untuknya. Akhirnya, dia mengambil sebuah tongkat ( holly, sebelas inci, inti bulu phoenix, 'bagus dan lentur' ) dan merasakan kehangatan di jari-jarinya. Ollivander menyatakan bahwa sangat penasaran bahwa Harry ditakdirkan untuk tongkat itu ketika saudaranya memberi Harry bekas lukanya. Hagrid mengajak Harry mencari makan di dunia Muggle, tapi Harry khawatir dia tidak akan cocok di Hogwarts karena semua orang mengharapkan hal-hal hebat darinya.

Untuk ulang tahun Harry, Hagrid membelikan Harry seekor burung hantu bersalju bernama Hedwig . Hagrid memberi Harry tiket kereta api , memberinya tanggal, waktu, dan lokasi untuk naik Hogwarts Express dan memberi tahu Harry bahwa jika dia membutuhkan sesuatu, dia harus menulis surat, dan Hedwig akan tahu di mana menemukannya. Harry naik kereta kembali ke keluarga Dursley.

Bab 6: Perjalanan dari Platform Sembilan Tiga Perempat
" Cara yang lucu untuk pergi ke sekolah penyihir, dengan kereta api. Karpet ajaib semuanya bocor, bukan? "
— Vernon Dursley mengejek Harry tentang perjalanan ke Hogwarts
PS C6
Kartu Katak Coklat Dumbledore

Bulan terakhir Harry bersama keluarga Dursley melegakan sekaligus menyedihkan. Bibi dan pamannya berpura-pura Harry tidak ada di sana, dan Dudley menjadi sangat takut pada sepupunya sehingga dia menolak berada di dekatnya. Harry menyendiri di kamar terkecil bersama Hedwig sebagai teman saat dia membaca buku-buku barunya.

Sehari sebelum dia berangkat, Harry meminta Paman Vernon untuk membawanya ke Stasiun King's Cross . Paman Vernon setuju untuk membawanya tetapi mengejeknya karena mengatakan dia harus berangkat dari Peron Sembilan dan Tiga Perempat, seperti yang ditandai pada tiket yang diberikan Hagrid kepadanya.

Keesokan harinya, keluarga Dursley meninggalkan Harry di stasiun. Dia berdiri di antara Peron Sembilan dan Sepuluh , bertanya-tanya bagaimana menemukan Peron Sembilan dan Tiga Perempat. Dia bingung untuk beberapa saat sampai dia mendengar Molly Weasley menggunakan kata "muggle" dan meminta bantuannya. Dia menyuruhnya untuk berlari melewati penghalang antara Peron Sembilan dan Sepuluh, yang dia lakukan, dan dia terkejut menemukan kereta ke Hogwarts di sisi lain stasiun.

Putra kembar Mrs Weasley, Fred dan George Weasley tahun ketiga , membantunya mengangkat kopernya ke kereta sebelum mengenalinya sebagai Harry Potter, dan adik laki-laki mereka Ron , siswa tahun pertama, meminta untuk duduk bersamanya.

Harry dan Ron bersatu karena kecemasan mereka terhadap Hogwarts (khususnya kakak laki-laki Ron yang sukses dan tikusnya yang menyedihkan, Scabbers ), dan Harry membeli banyak permen untuk mereka bagikan. Ron memperkenalkan Harry pada elemen dunia sihir seperti Quidditch , Kacang Segala Rasa Bertie Bott , dan kartu Penyihir dan Penyihir Terkenal . Salah satu kartu Harry bergambar Albus Dumbledore .

Harry juga bertemu dengan seorang gadis menyebalkan dan berprestasi bernama Hermione Granger , seorang anak laki-laki bernama Neville Longbottom yang telah kehilangan kataknya, Trevor, dan anak laki-laki yang tidak menyenangkan dari Madam Malkin, bernama Draco Malfoy , dan teman-temannya Crabbe dan Goyle .

Harry tersinggung oleh kefanatikan dan kekasaran Draco, terutama ketika diarahkan pada Ron, dan dia menolak tawaran persahabatan dan nasihatnya. Kelima anak laki-laki itu hampir berkelahi, tapi Scabbers menggigit Goyle dan mengusir mereka.

Hogwarts Express tiba di Stasiun Hogsmeade , dan Hagrid mengantar siswa tahun pertama melintasi Danau dengan perahu, tempat mereka melihat sekilas Hogwarts untuk pertama kalinya.

Bab 7: Topi Seleksi
" Kalau saja topi itu menyebut rumah untuk orang-orang yang merasa sedikit mual, pasti itulah rumah yang cocok untuknya. "
— Harry, tentang Topi Seleksi
PS C7
Peeves, menjatuhkan barang pada siswa tahun pertama yang baru

Para siswa baru disambut di pintu kastil oleh Profesor Minerva McGonagall , yang memberi tahu mereka bahwa mereka akan segera disortir ke dalam rumah mereka. Semua siswa Hogwarts tinggal di salah satu dari empat asrama: Gryffindor , Hufflepuff , Ravenclaw , atau Slytherin , dengan masing-masing asrama memiliki tim Quidditch sendiri . Asrama-asrama tersebut berkompetisi selama setahun satu sama lain untuk mendapatkan poin terbanyak, yang diperoleh dari keberhasilan dalam permainan Quidditch dan diberikan oleh guru untuk prestasi akademik dan kalah karena pelanggaran siswa, untuk memenangkan Piala Asrama yang diberikan di akhir. tahun.

Siswa tahun pertama menunggu di ruang depan sementara McGonagall memeriksa apakah sudah waktunya. Hantu Hogwarts tidak sengaja masuk ke dalam ruangan sambil berdebat apakah akan menawarkan Peeves kesempatan lagi.

Para siswa dibawa ke Aula Besar , di mana seluruh sekolah dan topi tua usang di bangku sedang menunggu mereka. Ketika para siswa mencoba Topi Seleksi , ia mengumumkan rumah tempat mereka ditempatkan. Harry menjadi sangat gugup. Dia telah belajar bahwa dia tidak peduli dengan asrama Slytherin, karena para siswa di dalamnya tidak menyenangkan dan Voldemort pernah menjadi milik Slytherin. Hermione Diurutkan ke dalam Gryffindor, Ron sangat tidak senang. Akhirnya giliran Harry yang memakai topi itu. Dia diam-diam berkata pada dirinya sendiri, "bukan Slytherin, bukan Slytherin!" Topi tertarik dengan ini.

Setelah diskusi mental singkat dengan topi yang mencoba menyarankan Slytherin kepadanya, topi itu menempatkan Harry di Gryffindor. Harry senang mengetahui Ron bergabung di Gryffindor bersamanya. Draco Malfoy ditempatkan di Slytherin.

Semua orang duduk untuk pesta besar untuk memulai tahun ini. Harry kewalahan dengan variasi makanan lezat yang disajikan. Sir Nicholas de Mimsy-Porpington , hantu penduduk Gryffindor (dikenal sebagai Nick Si Kepala-Nyaris-Putus karena pemenggalan kepala yang gagal), memperkenalkan dirinya kepada siswa tahun pertama dan memberi tahu mereka bahwa dia berharap mereka akan memenangkan kejuaraan asrama tahun ini. Saat hidangan penutup, diskusi beralih ke pendidikan siswa. Seorang siswa bernama Neville Longbottom menceritakan bagaimana keluarganya mengira dia adalah seorang Squib sampai dia selamat dari jatuh dari jendela. Siswa lainnya, Seamus Finnigan , berbicara tentang bagaimana ayahnya, seorang Muggle, terkejut ketika mengetahui istrinya (ibu Seamus) adalah seorang penyihir. Harry melirik ke sekeliling ruangan dan memperhatikan beberapa guru berbicara satu sama lain. Salah satu dari mereka, saat berbicara dengan Quirrell, menatap tajam ke arah Harry, yang langsung merasakan sakit yang menusuk di bekas luka di dahinya. Harry bertanya kepada Percy sang prefek siapa dia, dan mengetahui bahwa pria ini adalah Profesor Severus Snape , yang mengajar Ramuan . Setelah hidangan penutup, Dumbledore bangun untuk menyampaikan pidato sambutannya. Dia menambahkan beberapa peringatan tentang menjauhi Hutan Terlarang dan menghindari koridor lantai 3 di sisi kanan sekolah sebelum menyuruh semua orang tidur di Ruang Bersama mereka . Dalam perjalanan, para Gryffindor bertemu dengan Peeves , seorang Poltergeist , dan setelah tiba, mereka bertemu dengan Nyonya Gemuk yang mengizinkan mereka masuk ke Menara Gryffindor setelah Percy memberinya kata sandi. Harry kesulitan tidur karena mimpi yang dialaminya. Di dalamnya, dia mengenakan sorban Profesor Quirrell, yang menuntut dia untuk pindah ke Slytherin. Dia menolak, dan hiasan kepala menjadi lebih berat di kepalanya. Malfoy dan Snape tampak menertawakannya, lalu mimpi itu berakhir dengan kilatan lampu hijau yang menyebabkan Harry terbangun di tengah malam dan tertidur lagi, segera melupakannya setelahnya.

Bab 8: Ahli Ramuan
" Ah, ya. Harry Potter. Selebriti baru kita . "
- Severus Snape
PS C8
Buku Ramuan

Harry mendapati kehidupan di Hogwarts asing dan aneh. Semua orang membicarakannya, dan orang dewasa sepertinya selalu ada saat dia melakukan kesalahan. Sulit untuk menemukan jalan ke kelas karena adanya seratus empat puluh dua tangga yang berganti-ganti dan pintu masuk yang rumit. Orang-orang dalam potret Hogwarts tidak membantunya, karena mereka mengabaikan beberapa siswa dan mengunjungi satu sama lain, begitu pula dengan hantu, yang selalu menakuti Harry ketika mereka meluncur melalui pintu yang dia coba buka. Hanya Nick si Kepala-Nyaris-Putus yang mengarahkan para Gryffindor baru ke arah yang benar, tetapi Peeves layak mendapat dua pintu terkunci dan tangga rumit setiap kali Harry berpapasan dengannya saat terlambat masuk kelas. Bahkan yang lebih buruk daripada Peeves jika memungkinkan adalah penjaga sekolah Argus Filch , yang mendapat sisi buruk dari Harry dan Ron pada pagi pertama mereka, ketika dia menemukan mereka mencoba memaksa masuk melalui pintu yang ternyata adalah pintu masuk. ke koridor lantai tiga di luar batas . Dia mengancam untuk mengunci mereka di ruang bawah tanah, tapi kedua anak laki-laki itu beruntung diselamatkan oleh Quirrell, yang sedang lewat.

Semua kelas menjadi sangat menarik bagi Harry, dengan satu-satunya pengecualian adalah Sejarah Sihir , yang diajarkan oleh Profesor Binns , dan dia belajar bahwa ada lebih banyak hal dalam sihir selain melambaikan tongkatnya dan mengucapkan beberapa kata-kata lucu. Di kelas Transfigurasi pertamanya pada hari Kamis, Profesor McGonagall mengubah mejanya menjadi babi dan kemudian kembali lagi sambil menjelaskan bagaimana Transfigurasi itu sendiri adalah salah satu sihir paling rumit dan berbahaya untuk dipelajari, dan siapa pun yang ketahuan mengotak-atiknya akan mengalaminya. untuk dilarang masuk kelas. Seluruh kelas sangat terkesan, namun segera menyadari bahwa mereka tidak akan mengubah furnitur menjadi binatang. Hanya Hermione yang mampu membuat kemajuan dalam mengubah korek api menjadi jarum, yang membuat McGonagall memberinya senyuman langka, tapi Harry lega melihat teman-temannya sama tersesatnya seperti dia. Ketika tiba waktunya untuk beralih ke kelas Pertahanan Terhadap Ilmu Hitam (kelas yang dinanti-nantikan semua orang) setiap pagi, pelajaran berubah menjadi lelucon, karena Quirrell terus melanjutkan cerita tentang perjalanannya di tahun sebelumnya, seperti seperti ketika dia mengusir vampir di Rumania (yang dia takuti akan kembali dan menangkapnya), dan ketika dia mendapatkan sorban dari seorang pangeran Afrika karena menyelamatkannya dari zombie yang merepotkan .

Saat sarapan di hari Jumat pertama, Hedwig datang dengan undangan minum teh dari Hagrid. Kemudian, di kelas Ramuannya , Harry menemukan bahwa Profesor Snape membencinya, mengejek Harry sebagai "selebriti baru kita" dan kemudian mempermalukan Harry karena ketidaktahuannya tentang bahan pembuatan ramuan. Harry membawa Ron bersamanya ke gubuk Hagrid untuk minum teh. Harry dan Ron bingung dengan anjing Hagrid yang besar dan tampak galak, Fang , tetapi ternyata dia lembut. Hagrid memberi tahu Harry bahwa dia bereaksi berlebihan terhadap perlakuan Snape, menyatakan bahwa Snape tidak punya alasan untuk membencinya. Harry kebetulan memperhatikan sebuah artikel dari surat kabar sihir, Daily Prophet , yang merinci pembobolan yang terjadi di bank Gringotts di brankas yang telah dikosongkan pada hari sebelumnya. Dia menyadari bahwa itu terjadi pada hari ulang tahunnya, hari dimana dia dan Hagrid pergi ke Gringotts. Lebih jauh lagi, dia ingat bahwa Hagrid mengosongkan lemari besi tujuh ratus tiga belas, membawa sebuah paket kecil bersamanya saat dia pergi. Harry meninggalkan Hagrid, pikirannya dipenuhi pertanyaan.

Bab 9: Duel Tengah Malam
" Kita semua bisa saja dibunuh - atau lebih buruk lagi, diusir. Sekarang kalau kamu tidak keberatan, aku mau tidur. "
— Hermione mengeluh tentang "petualangan" mereka
PS C9
Harry dan Ron memasuki ruang rekreasi Gryffindor

Harry telah berada di Hogwarts selama sekitar dua minggu ketika dia mengetahui bahwa anak -anak Gryffindor akan mendapat pelajaran terbang bersama anak-anak Slytherin , yang sangat tidak dia sukai. Harry tidak ingin menghabiskan lebih banyak waktu dengan Malfoy daripada yang seharusnya. Namun, Harry menyadari bahwa dia cukup alami dalam terbang. Madam Hooch memimpin kelas, dengan lembut mengirimkan brosur baru itu ke tanah. Neville mengalami kecelakaan ketika sapunya mengamuk dan pergelangan tangannya patah. Madam Hooch membawanya ke Rumah Sakit Wing memberitahu semua orang untuk tetap di tanah saat dia pergi. Malfoy memperhatikan Remembrall milik Neville, mengambilnya, dan mulai terbang bersamanya. Harry mengejar Malfoy, yang melempar bola ke udara. Harry menangkapnya dengan spektakuler dan mendarat kembali dengan selamat di tanah. Saat itu, Profesor McGonagall tiba, menegur Harry dan memerintahkan dia untuk mengikutinya. Namun alih-alih menghukumnya, McGonagall memperkenalkannya kepada Oliver Wood , kapten tim Quidditch Gryffindor , dan menjadikannya Seeker baru di tim Gryffindor.

At dinner, Harry excitedly tells Ron about joining the Quidditch team but tells him that Wood wants it to be a secret. Malfoy comes over with his cronies Vincent Crabbe and Gregory Goyle and teases Harry about getting in trouble earlier. The tension grows and Malfoy challenges Harry to a wizard's duel. Harry accepts, in spite of Hermione's attempt to dissuade them from breaking the school rules. As Harry and Ron sneak out later that night, Hermione tries to stop them but gets locked out of the dorm (the Fat Lady has gone for an evening stroll) and must tag along. Neville also joins them, as he has forgotten the password to the common room and ended up sleeping on the floor outside. They arrive at the Trophy Room, the site of the duel, but Malfoy is nowhere to be found. Suddenly, they hear Argus Filch and his cat, Mrs Norris, enter the room. With it obvious that Malfoy tricked them, they begin to hide and then run away. Not sure where they are going, they accidentally end up in the forbidden area on the third floor, staring at a large and scary three-headed dog. The children manage to get back to their dorm safely, though they are terrified. Hermione reprimands Harry, but stirs his curiosity by pointing out that the dog was standing on a trapdoor.

Chapter 10: Hallowe'en
"But from that moment on, Hermione Granger became their friend. There are some things you can't share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them."
— The beginning of the trio's great friendship
PS C10
Troll in the dungeon

Keesokan paginya, Harry dan Ron sedang mendiskusikan apa yang mungkin dijaga anjing itu ketika surat tiba. Harry menerima Nimbus 2000 , sapu balap, bersama dengan catatan dari Profesor McGonagall yang memanggilnya ke latihan Quidditch. Malfoy memberi tahu Harry bahwa siswa tahun pertama tidak diperbolehkan menggunakan sapu. Malfoy kemudian mencoba melaporkan Harry kepada Profesor Flitwick yang baru saja mengungkapkan kekagumannya atas bakat Harry setelah mendengar dari McGonagall. Harry kemudian bertemu Oliver Wood untuk mempelajari dasar-dasar Quidditch, termasuk berbagai posisi dalam tim Quidditch standar dan peralatan yang digunakan dalam permainan. Oliver menjelaskan peran Harry sebagai Seeker : tugasnya adalah menghindari pemain lain dan menangkap Golden Snitch . Permainan Quidditch tidak dapat berakhir sampai Snitch ditangkap, menjadikan Seeker sebagai pemain terpenting dalam sebuah tim. Di Hallowe'en, Flitwick mulai mengajari murid-muridnya cara membuat benda terbang, menggunakan mantra Wingardium Leviosa . Hanya Hermione yang berhasil; Ron, tersinggung oleh sikap superioritasnya, melontarkan komentar buruk yang sengaja didengar Hermione. Harry memperhatikan dia berlari sambil menangis.

Harry dan Ron tiba di pesta Hallowe'en untuk mendengar Profesor Quirrell , guru Pertahanan Terhadap Ilmu Hitam , menyerbu masuk dan memberikan pengumuman mengerikan tentang troll setinggi dua belas kaki di dalam gedung. Ketika para prefek menuntun para siswa kembali ke asrama mereka, Harry menyadari bahwa Hermione tidak tahu tentang troll itu. Mereka berangkat untuk memperingatkannya dan menemui troll itu. Tanpa disadari, mereka menguncinya di kamar mandi perempuan hanya untuk menyadari bahwa Hermione terjebak di sana bersama troll tersebut. Menggunakan kerja tim, sihir, dan banyak keberuntungan, keduanya berhasil melumpuhkan troll tersebut. Profesor McGonagall menemukan mereka dan mulai memarahi anak-anak itu. Hermione menyela bahwa Harry dan Ron sedang mencarinya. Dia kemudian berbohong, mengatakan bahwa dia sendiri yang menghadapi troll itu dan bahwa Ron dan Harry telah berusaha menyelamatkannya dari troll itu. Pada titik ini, Hermione berteman dengan mereka.

Bab 11: Quidditch
" Flint hampir membunuh Seeker Gryffindor, dan itu bisa terjadi pada siapa pun, saya yakin. "
— Lee Jordan , mengomentari pertandingan Quidditch
PS C11
Pertandingan Quidditch Gryffindor vs Slytherin

Saat bulan November dimulai, begitu pula musim Quidditch , dan Harry akan memainkan pertandingan pertamanya melawan Slytherin. Untuk persiapannya, Harry meminjam buku berjudul Quidditch Through the Ages dari Hermione. Profesor Snape menemukan Ron, Harry, dan Hermione keluar membawa buku itu pada suatu malam dan menyita buku itu dari Harry dengan dalih bahwa buku perpustakaan tidak boleh dibawa ke luar sekolah, yang diyakini Harry sebagai alasan yang lemah. Kecurigaan Harry terhadap Snape terus bertambah. Harry mulai memperhatikan bahwa Snape pincang. Pergi untuk mengambil buku itu dari Snape, Harry sengaja mendengar Snape berbicara dengan Argus Filch tentang fakta bahwa anjing berkepala tiga telah menyerangnya, meninggalkan luka di kakinya, yang membuat Harry semakin curiga.

Keesokan paginya, pertandingan Quidditch dimulai. Harry melihat Golden Snitch di awal permainan dan terbang ke arahnya ketika Kapten Slytherin mendorongnya keluar dan dihukum. Kemudian dalam permainan, sapu Harry mulai menyentak tak terkendali. Hagrid berkomentar bahwa hanya Sihir Hitam yang bisa membuat sapu jadi sulit dikendalikan. Hermione memperhatikan bahwa Snape sedang menatap Harry dan bergumam pada dirinya sendiri, tanda-tanda kutukan. Ketika dua rekan satu tim Harry, si kembar Weasley, mencoba menyelamatkan Harry di udara, Hermione bergegas ke Snape dengan tergesa-gesa sehingga dia menjatuhkan Quirrell, menyelinap di belakang Snape, dan membakar jubahnya. Tiba-tiba, mantra pada sapu Harry rusak dan Harry sekali lagi memegang kendali. Dia mulai melaju kencang menuju tanah dan mendarat, menangkap Snitch di mulutnya dan hampir menelannya.

Hagrid membawa Harry kembali ke gubuknya bersama Hermione dan Ron, yang memberi tahu Harry bahwa Snape mengutuk sapunya. Hagrid tidak mempercayai hal ini, bertanya mengapa Snape mencoba membunuh Harry. Harry memberi tahu Hagrid tentang Snape yang terluka oleh anjing di koridor lantai tiga. Hagrid tanpa sadar mengungkapkan bahwa anjing berkepala tiga, Fluffy , adalah miliknya, dan bahwa apa yang dijaga anjing tersebut adalah rahasia yang hanya diketahui oleh Albus Dumbledore dan seorang pria bernama Nicolas Flamel .

Bab 12: Cermin Erised
Keluarga Potter tersenyum dan melambai pada Harry dan dia menatap balik ke arah mereka dengan lapar, tangannya menekan kaca seolah-olah dia berharap untuk jatuh menembus kaca itu dan meraih mereka. Dia merasakan semacam rasa sakit yang kuat di dalam dirinya, setengah gembira, setengah kesedihan yang mengerikan .
— Harry melihat ke Cermin Tarsah
PS C12
Harry mengamati Cermin Tarsah

Natal sudah dekat. Malfoy menggoda Harry tentang keharusan tinggal di Hogwarts selama liburan, karena dia tidak memiliki orang tua. Harry, bagaimanapun, berharap untuk menghabiskan Natal jauh dari keluarga Dursley, terutama karena Ron juga tinggal di Hogwarts, karena Tuan dan Nyonya Weasley akan mengunjungi kakak laki-laki Ron, Charlie di Rumania. Sehari sebelum liburan, Hermione mengalihkan perhatian Ron dan Harry dari percakapan dengan Hagrid untuk mencari di perpustakaan untuk informasi lebih lanjut tentang Nicolas Flamel. Pustakawan, Madam Pince , menangkap Harry berkeliaran di sekitar bagian buku terlarang di perpustakaan dan mengusirnya.

Pada Hari Natal, Harry dan Ron terbangun dan menerima hadiah, meskipun hadiah Harry lebih sedikit. Harry menerima seruling dari Hagrid, koin 50 pence dari keluarga Dursley , beberapa fudge dan Chocolate Frogs dari Hermione, dan jumper rajutan dari ibu Ron. Dia juga menerima jubah Gaib yang hanya disertai dengan catatan anonim yang memberitahukan kepadanya bahwa jubah itu pernah menjadi milik ayah Harry dan harus "digunakan dengan baik". Malam itu, setelah makan malam Natal yang memuaskan dan setelah Ron tertidur, Harry mencoba Jubah Gaibnya. Tanpa terlihat, dia bisa pergi ke bagian buku terbatas di perpustakaan. Tapi salah satu buku mulai berteriak ketika dia membukanya, jadi dia segera pergi. Dia melewati Filch dan bersembunyi di ruang kelas tua saat Filch meminta Snape membantunya mencari di koridor. Di dalamnya berdiri cermin tua berbingkai emas dengan tulisan "Erised stra ehru oyt ube cafru oyt on wohsi" ("Aku tidak menunjukkan wajahmu, tapi keinginan hatimu"). Harry melihat ke cermin dan melihat banyak orang berdiri di belakangnya, tetapi ketika dia berbalik ke dalam ruangan, dia tidak melihat siapa pun. Tiba-tiba, dia menyadari bahwa dua orang di cermin adalah ibu dan ayahnya yang telah meninggal . Dia mencoba untuk berbicara kepada mereka, tetapi mereka hanya dapat berkomunikasi dengan melambaikan tangan. Harry berlama-lama di sana beberapa saat tetapi akhirnya kembali ke kamarnya.

Malam berikutnya, Harry membawa Ron bersamanya ke ruang cermin. Ron tidak melihat orang tua Harry di cermin melainkan melihat dirinya memegang Piala Quidditch . Nyonya Norris, kucing Filch yang berkeliaran, memperhatikan mereka. Pada malam ketiga, Ron takut ketahuan dan tidak ingin kembali, karena dia tidak mempercayai cermin, jadi Harry kembali sendirian. Di sana dia menemukan Albus Dumbledore. Dumbledore menjelaskan kepada Harry bahwa cermin, yang dikenal sebagai Cermin Erised , menampilkan keinginan terdalam siapa pun yang melihatnya. Harry lega mengetahui bahwa Dumbledore tidak marah. Namun, dia memperingatkan Harry bahwa manusia telah menjadi sia-sia dan menjadi gila di depan cermin dan memberi tahu Harry bahwa cermin itu akan dipindahkan ke lokasi baru dan menyuruhnya untuk tidak mencarinya. Ketika Harry bertanya apa yang dilihat Dumbledore di cermin, jawabannya adalah "dirinya memegang sepasang kaus kaki."

Bab 13: Nicolas Flamel
" Saya tidak pernah berpikir untuk mencari di sini!" dia berbisik penuh semangat. "Aku mengeluarkan ini dari perpustakaan beberapa minggu yang lalu untuk membaca sedikit. "
— Hermione, mengingat Nicolas Flamel
Harry sulit melupakan gambaran orangtuanya. Latihan Quidditch berlanjut lebih keras lagi dan terungkap bahwa Snape akan menjadi wasit pertandingan berikutnya. Malfoy melakukan kutukan pengunci kaki pada Neville, dan untuk menghiburnya, Harry memberi tahu Neville bahwa dia "Bernilai dua belas dari Malfoy." Harry tiba-tiba teringat bahwa dia membaca nama Nicolas Flamel di kartu katak coklat, yang mengingatkan Hermione bahwa dia pernah melihat nama itu di buku yang dia ambil dari perpustakaan, dan tim menemukan bahwa dia adalah seorang alkemis terkenal yang merupakan satu-satunya yang diketahui. pembuat Batu Bertuah , yang kekuatannya meliputi mengubah logam apa pun menjadi emas dan menghasilkan Ramuan Kehidupan , ramuan yang dapat membuat peminumnya abadi.

PS C13
Severus Snape memasuki Hutan Terlarang

Pertandingan Quidditch Gryffindor versus Hufflepuff tiba dan Snape, yang menjadi wasit pertandingan, diperkirakan bias, sementara di tribun Ron dan Neville terlibat perkelahian dengan Malfoy, Crabbe, dan Goyle setelah Malfoy membuat komentar kasar terhadap para pemain tim asrama mereka. serta keduanya. Harry menangkap pengadu dan memenangkan pertandingan di bawah lima menit, meskipun Ron tidak melihat ini karena melawan Draco Malfoy, dan Neville dikirim ke rumah sakit karena cedera yang dideritanya saat melawan Crabbe dan Goyle. Kemudian, Harry memperhatikan dan mengikuti Snape ke Hutan Terlarang dengan sapu di mana dia bertemu Quirrell dan mereka berbicara tentang Batu Bertuah . Harry berpikir bahwa Snape sedang mencoba memaksa Quirrell untuk membantunya mendapatkan batu itu sehingga dia bisa menjadi kaya, yang membuat Ron dan Hermione khawatir karena takut Quirrell akan berbicara.

Bab 14: Norbert si Punggung Bukit Norwegia
" Tapi itu melanggar hukum kita,...Pembiakan naga dilarang oleh Konvensi Penyihir tahun 1709, semua orang tahu itu. "
— Ron, memperingatkan Hagrid setelah mengetahui tentang Norbert
PS C14
Norbert, baru menetas

Harry, Ron dan Hermione bertemu dengan Hagrid, yang memastikan Batu itu disimpan di Hogwarts. Hermione memikatnya untuk berbicara tentang mantra yang digunakan untuk menjaganya: Fluffy, anjing berkepala tiga, adalah milik Hagrid, bersama dengan mantra dari Profesor Sprout , Flitwick , McGonagall , Quirrell , dan Snape . Setelah ini, Harry mengeluh tentang suhu tinggi di gubuk Hagrid, hanya untuk mengetahui bahwa dia memiliki telur naga Punggung Bukit Norwegia , yang dia beri nama Norbert setelah menetas. Malfoy, yang sedang memata-matai, menemukan naga itu. Untuk mengatasi masalah tersebut, mereka meyakinkan Hagrid untuk mengirim naga itu ke saudara laki-laki Ron, Charlie. Tangan Ron digigit naga, dan dia dikirim ke Madam Pomfrey. Harry dan Hermione menyelundupkan Norbert dalam peti ke menara tertinggi di bawah jubah Gaib Harry dan dalam perjalanan mereka melihat Profesor McGonagall menyeret Malfoy ke tahanan karena bangun dari tempat tidur di malam hari dan mengatakan "kebohongan" tentang Harry dan seekor naga. Mereka menyerahkan peti itu kepada teman-teman Charlie , dan kembali menuruni tangga, di mana mereka bertemu dengan Filch, terlambat menyadari bahwa mereka telah meninggalkan Jubah Gaib.

Bab 15: Hutan Terlarang
" Semoga berhasil, Harry Potter...Sebelumnya planet-planet telah salah dibaca, bahkan oleh para centaur. Kuharap ini adalah salah satu saat yang tepat. "
— Firenze mengucapkan selamat tinggal pada Harry
PS C15
Firenze, sang centaur

Filch membawa Harry dan Hermione ke kantor McGonagall , tempat mereka bertemu Neville. McGonagall, sangat kecewa, mengambil masing-masing 50 poin dari mereka bertiga dan memberi mereka semua penahanan, yang akan mereka layani bersama Malfoy. Popularitas mereka di mata siswa lain menurun karena hal ini. Sekitar seminggu sebelum ujian, Harry mendengar Profesor Quirrell, terdengar seolah dia sedang diancam. Jadi, Harry pergi ke perpustakaan untuk memberi tahu Ron dan Hermione. Mereka yakin Snape mengancam Quirrell dan bermaksud mencuri Batu itu segera, dan Hermione menyarankan agar mereka pergi ke Dumbledore. Harry menolak, mengatakan bahwa mereka tidak punya bukti.

Harry, Hermione, dan Neville menerima catatan dari Profesor McGonagall yang memberitahukan mereka bahwa penahanan mereka akan dimulai pukul sebelas malam itu. Filch membawa mereka ke Hutan Terlarang , tempat Hagrid menunggu untuk membawa mereka untuk melakukan sedikit penyelidikan. Hagrid menunjukkan kepada mereka darah unicorn perak dan mengatakan mereka perlu menemukan unicorn yang terluka. Mereka berpisah, dengan Hagrid membawa Harry dan Hermione, dan Neville dan Malfoy pergi bersama Fang . Hagrid bertemu dengan beberapa centaur , bernama Ronan dan Bane , namun tidak mendapat informasi berguna dari mereka. Tiba-tiba, Hagrid melihat percikan merah di udara, menandakan pihak lain sedang dalam masalah. Dia berlari ke arah mereka dan kembali, memarahi Malfoy karena mengejutkan Neville hingga mengirimkan percikan api. Hagrid mengganti Harry dan Neville, malah mengirim Harry pergi bersama Malfoy. Mereka akhirnya menemukan unicorn mati dan melihat sesuatu meminum darahnya. Malfoy berteriak dan berlari bersama Fang, meninggalkan Harry yang diselamatkan dari sosok centaur bernama Firenze , yang memberi tahu Harry bahwa darah unicorn dapat membuatmu tetap hidup, bahkan jika kamu berada satu inci dari kematian, tetapi mengutukmu dengan setengah- hidup dalam prosesnya. Dia kemudian mengungkapkan bahwa orang yang meminumnya melakukannya untuk tetap hidup sampai mereka dapat meminum Ramuan Kehidupan dan menginginkan Batu tersebut. Dia juga bertanya pada Harry apakah dia tidak akan mengenal siapa pun yang telah menunggu bertahun-tahun untuk mendapatkan kembali kekuasaan dan Harry menyadari bahwa sosok misterius itu adalah Voldemort yang lemah namun masih hidup .

Kembali ke ruang rekreasi, Harry memberi tahu Hermione dan Ron Voldemort di hutan dan bahwa Snape menginginkan Batu itu untuk membantu Voldemort memulihkan kekuatannya. Setelah itu, saat masuk ke tempat tidurnya, Harry menemukan bahwa Jubah Gaibnya telah dikembalikan kepadanya.

Bab 16: Melalui Pintu Jebakan
" Aku tidak tahu bagaimana kamu mengetahui tentang Batu itu, tapi yakinlah, tidak ada yang mungkin bisa mencurinya, batu itu terlindungi dengan sangat baik. "
— Pernyataan Profesor McGonagall yang salah tentang keamanan batu itu
PS C16
Lembutkan anjing berkepala tiga

Setelah menyelesaikan ujian mereka, Harry menyadari kebetulan yang mencurigakan di mana Hagrid menginginkan seekor naga lebih dari apa pun, hanya untuk bertemu dengan orang asing yang memiliki naga untuk diberikan kepadanya. Dia, Ron, dan Hermione berlari untuk bertanya kepadanya tentang pria yang memberikan Norbert kepadanya, dan dia bilang dia tidak pernah melihat wajahnya karena dia terus mengenakan tudung. Hagrid juga menyebutkan bahwa mereka berbicara tentang Hogwarts dan Fluffy si anjing berkepala tiga. Dia juga menyebutkan bahwa orang asing itu memberinya minuman sambil mendapatkan informasi darinya. Hagrid melewatkan cara melewati Fluffy, yang membuat Harry, Ron, dan Hermione pergi. Mereka menuju kantor Dumbledore , hanya untuk melihat McGonagall, yang memberi tahu mereka bahwa dia telah berangkat ke London. Setelah Harry mengungkapkan bahwa mereka tahu tentang Batu itu, McGonagall menegaskan tidak ada yang bisa mencuri Batu itu . Ketiganya menyadari bahwa Dumbledore telah dibujuk dan Snape mengejar Batu itu malam itu sehingga mereka memutuskan untuk keluar malam itu untuk mencoba mendapatkannya sendiri. Setelah Hermione mengutuk Neville dengan Kutukan Pengikat Seluruh Tubuh karena menolak mengizinkan mereka pergi, mereka menuju ke ruang lantai tiga dan memulai perjalanan intens mereka ke tujuh Kamar Batu Bertuah . Mereka menemukan pintu terbuka, dan harpa tergeletak di lantai. Harry memainkan seruling yang diberikan Hagrid untuk Natal, dan Fluffy kembali tidur. Mereka menuju ke bawah melalui pintu jebakan. Mereka mendarat di kamar Profesor Sprout, penuh dengan Jerat Setan , yang hampir membekap mereka sebelum Hermione menyalakan api dan mematikannya.

Kamar sebelah, kamar Profesor Flitwick, menyimpan sekumpulan kunci terbang dan beberapa sapu. Harry menemukan yang perak dengan sayap patah yang berbeda dari yang lain dan menangkapnya, membuka kunci pintu berikutnya dengannya. Kamar berikutnya adalah kamar Profesor McGonagall, dan memiliki papan catur besar, untuk permainan Catur Penyihir yang Ron bantu mereka menangkan, dengan mengorbankan dirinya sendiri dan tersingkir. Harry dan Hermione melanjutkan ke kamar berikutnya, kamar Profesor Quirrell, di mana mereka menemukan troll tak sadarkan diri tergeletak di lantai. Terakhir, mereka memasuki kamar Profesor Snape dan menemukan tujuh ramuan dalam botol bersama dengan gulungan kertas yang memberikan petunjuk mana yang harus diminum untuk melanjutkan, mencatat bahwa tiga botol berisi racun, dua berisi anggur jelatang, satu akan mengirim peminumnya kembali, dan yang lainnya. yang lain akan membiarkan peminumnya maju ke ruangan berikutnya. Hermione memberi tahu Harry bahwa ini adalah ujian logika dan bukan sihir yang membuat sebagian besar penyihir gagal. Dia memecahkan teka-teki itu, dan atas instruksi Harry, meminum minuman yang memungkinkannya kembali melewati api ungu, sementara Harry meminum minuman yang menuju ke api hitam dan ke ruangan terakhir, di mana dia terkejut melihat siapa yang dia lihat. .

Bab 17: Pria Berwajah Dua
" Mencoba menakutiku - seolah-olah dia bisa, padahal Lord Voldemort ada di sisiku... "
— Quirrell, berbicara dengan Harry tentang Snape
PS C17
Profesor Quirrell melepas sorbannya

Quirrell-lah yang dilihat Harry di ruangan itu, bukan Snape. Harry, tercengang, mendengar Quirrell memberitahunya bahwa, selain Snape, tidak ada yang mengira dia akan mencoba mencuri Batu itu dan bahwa Snape sebenarnya melindungi Harry. Harry memperhatikan Cermin Erised , dan Quirrell berhenti untuk memeriksanya, mengatakan itu adalah kunci untuk mendapatkan Batu itu. Untuk mengalihkan perhatiannya dari Cermin, Harry mempertanyakan Quirrell, yang mengatakan dia melayani Lord Voldemort , dan meskipun Snape membenci Harry karena ayahnya, dia tidak pernah ingin Harry mati. Dia menjelaskan bagaimana ayah Snape dan Harry bersekolah bersama ketika mereka masih muda, dan bagaimana kebencian mereka terhadap satu sama lain bermula. Quirrell meminta bantuan dari tuannya untuk mendapatkan Batu itu , dan suara seperti ular menyuruhnya untuk menggunakan anak itu. Harry disuruh melihat ke Cermin. Dia melihat bayangannya mengeluarkan Batu itu dari sakunya dan memasukkannya kembali, dan Harry merasakan Batu itu jatuh ke dalam sakunya sendiri. Dia memberitahu Quirrell bahwa dia melihat dirinya berjabat tangan dengan Dumbledore, setelah memenangkan Piala Asrama untuk Gryffindor. Suara seperti ular memberitahu Quirrell bahwa Harry berbohong dan Quirrell melepas sorbannya untuk menunjukkan kepada Harry apa yang ada di belakang kepalanya. Saat Quirrell berbalik, Harry terkejut melihat wajah lain di mana seharusnya bagian belakang kepala Quirrell berada. Wajahnya memiliki mata merah dan celah seperti ular di tempat hidung seharusnya berada. Harry menyadari ini adalah wajah Voldemort dan Voldemort meminta Harry memberinya Batu itu. Harry menolak dan lari, tapi Quirrell menangkapnya. Namun, kontak dengan kulit Harry membakar Quirrell dan menyebabkan dia mempunyai bisul di seluruh area di mana Harry menyentuhnya. Harry meraih wajah Quirrell, lalu lengannya, dan bertahan, dengan rasa sakit yang menyilaukan di kepalanya, sampai dia merasakan lengannya dicabut sebelum dia pingsan.

Dia terbangun di sayap rumah sakit bersama Dumbledore di sana, memberitahunya bahwa Quirrell tidak berhasil mendapatkan Batu itu, dan memang Batu itu telah dihancurkan. Meskipun demikian, ada cara lain agar Voldemort dapat kembali. Dia tidak bisa dibunuh, dan dia membiarkan Quirrell mati. Dumbledore menjelaskan alasan mengapa Quirrell tidak bisa menyentuh Harry adalah karena ibu Harry telah meninggal untuk menyelamatkannya, melindunginya dengan cintanya . Harry juga memberi tahu Dumbledore tentang apa yang dikatakan Quirrell kepadanya sebelumnya mengenai Snape yang membenci Harry karena kebenciannya pada ayahnya . Dumbledore menjawab bahwa Snape hanya dengan enggan melindungi Harry tahun ini untuk melunasi hutangnya karena James Potter menyelamatkan nyawanya selama tahun-tahun mereka di Hogwarts. Harry kemudian menerima kunjungan dari Ron dan Hermione, yang mengungkapkan bahwa Slytherin menjadi yang pertama untuk Piala Asrama dan, karena Harry tidak dapat bermain dalam pertandingan kejuaraan Quidditch, Ravenclaw dengan mudah memenangkan pertandingan tersebut, sebelum Madam Pomfrey memaksa mereka keluar. Hagrid muncul kemudian dan memberi Harry buku berisi foto orang tua dan keluarganya.

Keesokan harinya, di pesta akhir semester , Dumbledore memberikan beberapa poin di menit-menit terakhir untuk kejadian terkini. Dia memberi Ron dan Hermione masing-masing lima puluh poin, dan Harry enam puluh, yang menempatkan mereka setara dengan Slytherin untuk tempat pertama. Dumbledore kemudian menyadari bahwa meskipun sulit untuk melawan musuh, bahkan lebih sulit lagi untuk melawan teman seperti yang dilakukan Neville, dan dia memberi Neville 10 poin lagi, yang merupakan poin rumah terbanyak yang pernah didapat Neville. Hal ini menempatkan Gryffindor memimpin dan menjadi pemenang Piala Asrama, yang membuat semua orang gembira kecuali para Slytherin. Tidak hanya siswa Gryffindor yang senang, tetapi Hufflepuff dan Ravenclaw juga senang melihat kejatuhan Slytherin. Segera, koper mereka sudah dikemas, dan mereka naik Hogwarts Express kembali menuju dunia muggle. Harry, Ron dan Hermione semua mengucapkan selamat tinggal sebelum pulang.
    </main>
  );
}

export default Content;
